package com.hanwen.politiciansAU;

import java.util.ArrayList;
import java.util.List;

public class People {

    private String name;
    private int imageId;
    private int imageFactionId;
    private String desc;

    public People(String name, int imageId, int imageFactionId, String desc) {
        this.name = name;
        this.imageId = imageId;
        this.imageFactionId = imageFactionId;
        this.desc = desc;
    }

    public static List<People> getAllPeoples() {
        List<String> descsLiberal = new ArrayList<String>();
        List<String> descsLabor = new ArrayList<String>();
        List<String> descsOther = new ArrayList<String>();
        //0
        descsLiberal.add("The Liberal Party of Australia is a major centre-right political party in Australia, one of the two major parties in Australian politics, along with the centre-left Australian Labor Party (ALP). It was founded in 1944 as the successor to the United Australia Party (UAP).\n" +
                "The Liberal Party is the largest and dominant party in the Coalition with the National Party of Australia. In two states and territories of Australia the parties have merged, forming the Country Liberal Party of the Northern Territory and the Liberal National Party of Queensland. Except for a few short periods, the Liberal Party and its predecessors have operated in similar coalitions since the 1920s. The party's leader is Scott Morrison and its deputy leader are Josh Frydenberg. The pair were elected to their positions at the August 2018 Liberal leadership ballot, with Frydenberg and Morrison as replacements for Julie Bishop and Malcolm Turnbull respectively, the latter of whom Morrison consequently succeeded as Prime Minister of Australia. Now the Morrison Government, the party had been elected at the 2013 federal election as the Abbott Government which took office on 18 September 2013. At state and territory level, the Liberal Party is in office in three states: Will Hodgman, Premier of Tasmania since 2014, Gladys Berejiklian, Premier of New South Wales since 2017 and Steven Marshall, Premier of South Australia since 2018. The party is in opposition in the states of Victoria, Queensland and Western Australia, and in both the Australian Capital Territory and the Northern Territory.\n");
        descsLiberal.add("Amanda Jane Stoker (born 30 October 1982) is an Australian politician and lawyer who has been a Liberal member of the Australian Senate representing Queensland since 21 March 2018, when she was appointed as a replacement for the Senate place of retiring Attorney-General George Brandis.\n" +
                "Stoker studied law at Sydney University, graduating with first-class honours, and began her career as a barrister in Brisbane with MinterEllison. She served as a Commonwealth prosecutor, as well as a judge's associate to Philip McMurdo in the Supreme Court of Queensland and to Ian Callinan in the High Court of Australia.\n" +
                "Leading up to the 2009 state election, Stoker sought pre-selection for the electoral district of Cleveland, which she lost to Mark Robinson who went on to win the seat. She was a Senate candidate with the LNP at the 2013 federal election.\n" +
                "On 10 March 2018, members of the Liberal National Party of Queensland (LNP) elected Stoker to succeed high-profile cabinet member George Brandis as a Senator for Queensland; she is the party's only female senator from that state. The Parliament of Queensland appointed Stoker to the casual vacancy left by Brandis on 21 March 2018 and she was sworn in as a Senator the following day.\n");
        descsLiberal.add("Anne Sowerby Ruston (born 10 June 1963) is an Australian Liberal Party politician serving as Minister for Families and Social Services since 2019, and has served as Senator for South Australia since 2012.\n" +
                "She served as Assistant Minister for International Development and the Pacific in the Morrison Government from August 2018 to May 2019, having previously been Assistant Minister for Agriculture and Water Resources in the Turnbull Government. She was appointed Minister for Families and Social Services in May 2019.\n");
        descsLiberal.add("Arthur Sinodinos AO (born 25 February 1957) is an Australian politician who has been a Senator for New South Wales since 2011, representing the Liberal Party. He served as a minister in the Abbott and Turnbull Governments.\n" +
                "Sinodinos was born in Newcastle, New South Wales, and attended the University of Newcastle. He subsequently worked as a public servant and political adviser, most notably as chief of staff to Prime Minister John Howard between 1997 and 2006. Before being elected to the Senate at the 2010 federal election, Sinodinos spent periods working for Goldman Sachs and the National Australia Bank. He was appointed Assistant Treasurer in the Abbott Government in 2013 but stepped aside from his ministerial duties in March 2014 during an investigation by the New South Wales Independent Commission Against Corruption (ICAC); he still formally held the position until resigning in December 2014. In September 2015, Sinodinos returned to the ministry as Cabinet Secretary in the Turnbull Government. He was made Minister for Industry, Innovation and Science in January 2017. He took a leave of absence from parliament in October 2017 due to ill health, and left the ministry in December 2017. In May 2019, it was announced that Sinodinos would be appointed the next Australian Ambassador to the United States.\n");
        descsLiberal.add("Bridget McKenzie (born 27 December 1969) is an Australian National Party politician serving as Minister for Agriculture since 2019, and has served as Senator for Victoria since 2011.\n" +
                "She has served as Deputy Leader of the National Party in the Parliament of Australia since December 2017, and shortly after her election to that position was appointed to Cabinet as Minister for Sport, Minister for Rural Health, and Minister for Regional Communications in the Turnbull Government.\n" +
                "Following the appointment of the Second Morrison Ministry in May 2019, Scott Morrison announced David Littleproud's previous ministerial positions were separated, with McKenzie appointed Minister for Agriculture and Littleproud as Minister for Water Resources.\n");
        descsLiberal.add("Dean Anthony Smith (born 15 May 1969) is an Australian politician and Liberal Party member of the Australian Senate since 2012, representing Western Australia.\n" +
                "Smith joined the Liberal Party at the age of 17, and later worked as a policy adviser to Premier of Western Australia Richard Court. In 1998, he was a senior advisor to Prime Minister John Howard during the Coalition's 1998 federal election campaign. In 2010, he founded Smith & Duda Consulting, a political lobbying firm, and also served as treasurer of the Liberal Party state branch in Western Australia.\n" +
                "Smith was appointed to the Senate on 2 May 2012 by a joint sitting of the Parliament of Western Australia, to fill a casual vacancy caused by the death of Senator Judith Adams.\n" +
                "Smith was the first openly-LGBTI member of the Parliament of Australia from the Liberal Party and has supported same-sex marriage in Australia since the 2014 Sydney hostage crisis. Prior to that, he opposed same-sex marriage and voted against it. Smith introduced the Marriage Amendment (Definition and Religious Freedoms) Bill 2017 to the Senate on 15 November and passed the Senate on 29 November 2017.\n" +
                "Smith was appointed Chief Government Whip in the Senate on 21 January 2019.\n" +
                "Smith is a member of a number of political and community organisations, including Australians for Constitutional Monarchy and the Australian National Flag Association.\n");
        descsLiberal.add("Eric Abetz (born 25 January 1958) is an Australian politician who has been a Senator for Tasmania since February 1994, representing the Liberal Party. He was the Minister for Employment and the Leader of the Government in the Senate in the Abbott Government from 2013 to 2015. He previously also served as Special Minister of State in the Howard Government from 2001 to 2006 and as Minister for Fisheries, Forestry and Conservation from 2006 to 2007.\n" +
                "Born in Germany, Abetz emigrated to Australia as a small child, when his father came to work for Tasmania's Hydro Electric Commission. He was educated at the University of Tasmania and was a barrister and solicitor before entering politics. He is a former national president of the Australian Liberal Students' Federation and was state president of the Tasmanian Liberals from 1990 to 1994.\n");
        descsLiberal.add("James William Paterson (born 21 November 1987) is an Australian politician who has been a Senator for Victoria since 2016, representing the Liberal Party.\n" +
                "Educated at McKinnon Secondary College and the University of Melbourne, Paterson worked as a special adviser for Senator Mitch Fifield, and for several months as an intern for U.S. congressman Lincoln Díaz-Balart. He then worked as a writer for the Victorian Employers' Chamber of Commerce and Industry (VECCI) before joining the Institute of Public Affairs (IPA) as editor of the IPA Review publication. In the IPA, Paterson was promoted to director of communications and development, before being promoted to deputy executive director in September 2014.\n");
        descsLiberal.add("Edwina Jane Hume (born 30 April 1971) is a Liberal member of the Australian Senate representing Victoria. She was elected at the 2016 election. Prior to her election, she was a senior policy adviser at AustralianSuper.\n" +
                "Born and raised in Melbourne, Hume completed a Bachelor of Commerce at the University of Melbourne, later returning to study political science. After graduating Hume held various senior positions in the financial services industry, working for the National Australia Bank, Rothschild Australia, Deutsche Bank and, immediately prior to her election, as a senior policy adviser at Australian Super.\n");
        descsLiberal.add("Andrew James Molan, AO, DSC (born 11 April 1950) is an Australian politician and former major general in the Australian Army. He has been a Senator for New South Wales since December 2017, representing the Liberal Party.\n" +
                "During his military career, Molan was commanding officer of the 6th Battalion, Royal Australian Regiment, commander of the 1st Brigade, commander of the 1st Division and its Deployable Joint Force Headquarters, and commander of the Australian Defence College. In April 2004, he deployed for a year to Iraq to serve as Chief of Operations for the new Headquarters Multinational Force in Iraq. He has been awarded the Distinguished Service Cross, as well as the Legion of Merit by the U.S. government. He retired from the army in 2008, and later that year released his first book, Running the War in Iraq.\n" +
                "Following his retirement from the army, Molan was appointed by the Abbott Government as a special envoy for Operation Sovereign Borders and was subsequently credited with being an architect of the coalition's Stop the Boats Australian border protection and asylum-seeker policies. In 2016, Molan unsuccessfully stood as a Liberal Party candidate for the Senate in New South Wales at the 2016 federal election. In December 2017, during the parliamentary eligibility crisis, the High Court declared him elected in place of Fiona Nash, who was ineligible to stand. \n");
        //10
        descsLiberal.add("John Gilbert Alexander OAM (born 4 July 1951) is an Australian politician and former professional tennis player.\n" +
                "As a tennis player, Alexander reached a career-high singles rank of no. 8 in the world in 1975. He reached the semi-finals of the Australian Open singles on three occasions, and won the doubles in 1975 and 1982. He also played in the Australian team that won the 1977 Davis Cup. After the end of his playing career, Alexander worked as a tennis commentator and managed various sports-related businesses.\n" +
                "Alexander won the Division of Bennelong for the Liberal Party at the 2010 election, and retained the seat in 2013 and 2016. He resigned effective 11 November 2017 due to constitutional ineligibility arising from his dual citizenship of the United Kingdom. He renounced his UK citizenship and stood as the Liberal Party candidate at the by-election, held on 16 December 2017, which he won.\n");
        descsLiberal.add("Jonathon Duniam (born 31 December 1982) is an Australian politician and a Liberal Party member of the Australian Senate representing the state of Tasmania. He was formerly Will Hodgman's deputy chief of staff, quitting in May 2016 to campaign in the Federal election. Duniam, the son of Waratah-Wynyard deputy mayor Mary Duniam, has a long history with the Liberal party, and was formerly president of the Young Liberals at 22.\n" +
                "Duniam grew up in Somerset, Tasmania on the North-West coast of the state. He attended Marist Regional College and the University of Tasmania, where he studied law, graduating with a Bachelor of Laws and Bachelor of Arts in 2006. While at university, he served as President of the University of Tasmania Liberal Club. He commenced his career in politics with the President of the Senate, Liberal Senator the Hon Paul Calvert in 2003 before joining Liberal Senator the Hon Eric Abetz as an adviser in 2005. He later worked for Liberal Senator the Hon Stephen Parry, then Chief Opposition Whip, as his Chief of Staff in 2009. From 2010 until before his election in 2016 Duniam was Deputy Chief of Staff to the Hon Will Hodgman MP, playing an instrumental role in the historic 2014 state election win.\n");
        descsLiberal.add("Joshua Anthony Frydenberg (born 17 July 1971) is an Australian politician who has been Treasurer of Australia and Deputy Leader of the Liberal Party since 24 August 2018. He has been a member of the Australian House of Representatives for the seat of Kooyong since August 2010.\n" +
                "Frydenberg served in various roles in the Abbott and Turnbull Governments from 2013 to 2018, including as Minister for Resources and Northern Australia, and as Minister for the Environment and Energy. On 24 August 2018, he was elected Deputy Leader of the Liberal Party following a leadership spill, which saw Scott Morrison elected as Leader. Morrison subsequently appointed Frydenberg Treasurer of Australia.\n");
        descsLiberal.add("Karen Lesley Andrews (born 23 August 1960) is an Australian politician who has been a member of the House of Representatives since 2010, representing the Division of McPherson in Queensland. She is a member of the Liberal National Party, and sits with the Liberal Party in parliament. She is the Minister for Industry, Science and Technology in the Morrison Government since August 2018. From 2014 until August 2018, Andrews served as a parliamentary secretary or assistant minister in the Abbott and Turnbull Governments. She has been Assistant Minister for Vocational Education and Skills since July 2016, having previously been Assistant Minister for Science.");
        descsLiberal.add("Kevin James Andrews (born 9 November 1955) is an Australian politician and member of the Liberal Party of Australia. He is currently a backbench Member of the House of Representatives for the seat of Menzies, to which he was first elected at the 1991 by-election. Andrews is a conservative and a Catholic.\n" +
                "Previously, Andrews served in the Howard Government as the Minister for Ageing, Minister for Employment and Workplace Relations, and then the Minister for Immigration and Citizenship until the 2007 election where his party lost government.\n" +
                "Following the 2009 Liberal leadership ballot, Andrews served in the Shadow Cabinet of Tony Abbott as shadow minister for Families, Housing and Human Services until the 2013 election where his party won government. In the Abbott Government, Andrews served in the cabinet as Minister for Social Services and later Minister for Defence. At the September 2015 Liberal leadership ballot, Andrews unsuccessfully contested for the Liberal deputy leadership against Julie Bishop, while supporting Tony Abbott against Malcolm Turnbull as Liberal leader. Upon the ascension of the Turnbull Government Andrews was dropped from the new Ministry and moved to the backbench.\n" +
                "With the retirement of Philip Ruddock at the 2016 federal election, Andrews became the Father of the House. While Warren Snowdon has a longer overall tenure in the House, Andrews is the longest continuously serving member. He is one of three parliamentary survivors of the Hawke government, the others being Snowdon and Russell Broadbent.\n");
        descsLiberal.add("Linda Karen Reynolds CSC (born 16 May 1965) is an Australian Liberal Party politician serving as Minister for Defence since 2019, and has served as Senator for Western Australia since 2014.\n" +
                "In 2013, Reynolds was elected from third position on the Liberal Senate ticket, but her place in the Senate was in doubt after the High Court ordered a fresh half-Senate election in Western Australia, after determining that there were missing ballot papers. However, Reynolds was successful in the re-run and her Senate term commenced on 1 July 2014. She was subsequently re-elected to the Senate in 2016.\n" +
                "Reynolds served as Assistant Minister for Home Affairs from August 2018 to March 2019. She was promoted to the Cabinet on 2 March 2019 by Scott Morrison as Minister for Defence Industry and Minister for Emergency Management and North Queensland Recovery.\n");
        descsLiberal.add("Marise Ann Payne (born 29 July 1964) is an Australian politician who has been Minister for Foreign Affairs in the Morrison Government since 2018, and was also appointed Minister for Women in 2019. She has been a Senator for New South Wales since 1997, representing the Liberal Party.\n" +
                "Payne was born in Sydney and attended the University of New South Wales. She was the first woman to serve as federal president of the Young Liberals (1989–1991). Payne was appointed to the Senate in 1997, in place of Bob Woods. She was elected to a full term in 2001, and has since been re-elected four more times. Payne was first added to the shadow ministry in 2007, and when the Coalition returned to power in 2013, she was made Minister for Human Services in the Abbott Government. Payne was appointed Minister for Defence when Malcolm Turnbull became prime minister, becoming the first woman to hold the position. After Turnbull was replaced by Scott Morrison in August 2018, it was announced that she would replace Julie Bishop as Minister for Foreign Affairs in the new government.\n");
        descsLiberal.add("Mathias Hubert Paul Cormann, born 20 September 1970) is an Australian Liberal Party politician serving as Minister for Finance in the Morrison Government since 2018, and has served as Senator for Western Australia since 2007. Cormann served as Minister for Finance in the Abbott and Turnbull Government from 2013 to 2018 and Minister for the Public Service from 2018 to 2019.\n" +
                "On 20 September 2015 Prime Minister Malcolm Turnbull promoted Cormann to the position of Deputy Leader of the Government in the Senate; and between February and July 2016 served as the Special Minister of State in the First Turnbull Ministry, after acting in the role since December 2015. Cormann is currently serving as the Leader of the Government in the Senate and the Vice-President of the Executive Council.\n");
        descsLiberal.add("Matthew James Canavan (born 17 December 1980) is an Australian politician. He was elected to the Australian Senate representing the state of Queensland at the 2013 federal election for the term beginning 1 July 2014. He is a member of the Liberal National Party. In the First Turnbull Ministry, Canavan served as the Minister for Northern Australia between 18 February and 19 July 2016.\n" +
                "With the reelection of the Turnbull Government in 2016, Canavan was elevated into Cabinet becoming the Minister for Resources and Northern Australia in the Second Turnbull Ministry.\n" +
                "On 25 July 2017, Canavan resigned from Cabinet over doubt as to his eligibility to be a member of the parliament, after discovering that he might be an Italian citizen. Section 44(i) of the Australian Constitution prohibits election of dual citizens to the Parliament of Australia. Italian constitutional experts were unable to advise with certainty whether he had inherited Italian citizenship, but the High Court found on 27 October 2017 that Canavan was not an Italian citizen and therefore was not ineligible under s 44(i).\n");
        descsLiberal.add("Michael Francis McCormack (born 2 August 1964) is an Australian politician who has been leader of the National Party and Deputy Prime Minister of Australia since February 2018. He is also Minister for Infrastructure, Transport and Regional Development, having previously served as Minister for Defence Personnel and Minister for Veterans' Affairs from 2017 to 2018. McCormack has been a member of the House of Representatives since 2010, representing the Division of Riverina in New South Wales. He was a newspaper editor before entering politics.");
        //20
        descsLiberal.add("Michaelia Clare Cash (born 19 July 1970) is an Australian politician who has been a Senator for Western Australia since July 2008, representing the Liberal Party. She is the Minister for Small and Family Business, Skills and Vocational Education in the Morrison Government, having previously been the Minister for Jobs and Innovation in the Turnbull Government, and before that Minister for Employment and Minister for Women from September 2015 to December 2017.");
        descsLiberal.add("Mitchell Peter Fifield (born 16 January 1967) is an Australian politician who has been a Senator for Victoria since 2004, representing the Liberal Party. He was a government minister in the Abbott, Turnbull, and Morrison Governments from 2013 to 2019. He served as Assistant Minister for Social Services (2013–2015), Manager of Government Business in the Senate (2013–2015), Minister for Communications (2015–2019), and Minister for the Arts (2015–2019).");
        descsLiberal.add("Scott John Morrison (born 13 May 1968) is an Australian politician serving as Prime Minister of Australia and Leader of the Liberal Party since 2018. He served as Treasurer of Australia from 2015 to 2018. Morrison was first elected Member of Parliament (MP) for Cook in 2007. Ideologically, he identifies himself as a pragmatic conservative.\n" +
                "\n" +
                "Morrison was born in Sydney and studied economic geography at the University of New South Wales. He worked as Director of the New Zealand Office of Tourism and Sport from 1998 to 2000 and was Managing Director of Tourism Australia from 2004 to 2006. Morrison was also State Director of the New South Wales Liberal Party from 2000 to 2004.\n" +
                "After his election to Parliament in 2007, Morrison was appointed to the opposition frontbench after the 2010 election. Following the Coalition's victory at the 2013 election, Morrison was appointed Minister for Immigration and Border Protection in the Abbott Government. In that capacity he was responsible for implementing Operation Sovereign Borders. In a 2014 cabinet reshuffle, Morrison was made Minister for Social Services. He was promoted to the role of Treasurer of Australia in September 2015, when Malcolm Turnbull became Prime Minister.\n" +
                "In August 2018, Peter Dutton challenged Turnbull for the leadership of the Liberal Party. Turnbull defeated Dutton, but tensions continued to mount and the party voted in favour of holding a second ballot; Turnbull chose not to be a candidate. In that second vote on 24 August, Morrison emerged as a compromise candidate, defeating Dutton and Julie Bishop to become Leader of the Liberal Party. He was sworn in as Prime Minister later that day. Morrison went on to lead the Coalition to an upset victory in the 2019 federal election.\n");
        descsLiberal.add("Simon John Birmingham (born 14 June 1974), an Australian politician, is a member of the Australian Senate representing South Australia as a member of the Liberal Party since 2007. Birmingham served as Parliamentary Secretary to the Minister for the Environment from 18 September 2013 then Assistant Minister for Education and Training in the Abbott Ministry from December 2014, before being promoted to Minister for Education and Training in the Turnbull Government from September 2015. Upon the installment of the Morrison Ministry in August 2018, he became the Minister for Trade, Tourism and Investment.");
        descsLiberal.add("Anthony John Abbott (born 4 November 1957) is an Australian politician who served as the 28th Prime Minister of Australia from 2013 to 2015 and Leader of the Liberal Party from 2009 to 2015. He served as Leader of the Opposition from 2009 to 2013. Abbott served as Member of Parliament (MP) for Warringah from 1994 to 2019.\n" +
                "Abbott was born in London to an Australian mother and a British father, and moved to Sydney at the age of two. He studied economics and law at the University of Sydney, and then attended The Queen's College, Oxford, as a Rhodes Scholar, studying Philosophy, Politics and Economics. After graduating from Oxford, Abbott briefly trained as a Roman Catholic seminarian, and later worked as a journalist, manager, and political adviser. In 1992, he was appointed director of Australians for Constitutional Monarchy, a position he held until his election to parliament at the 1994 Warringah by-election.\n" +
                "Abbott led the Coalition at the 2010 election, which resulted in a hung parliament. Following negotiations, Labor formed a Government with the support of one Greens MP and three independent MPs. Abbott was re-elected as Liberal Leader unopposed. He went on to lead the Coalition to victory at the 2013 election and was sworn in as the 28th Prime Minister of Australia on 18 September 2013. Abbott lost a Liberal Party leadership spill on 14 September 2015 and was replaced by Malcolm Turnbull as leader of the party and Prime Minister of Australia.\n");
        descsLiberal.add("Zdenko Matthew \"Zed\" Seselja (born 27 March 1977) is an Australian politician who has been a Senator for the Australian Capital Territory since 2013, representing the Liberal Party. He was previously a member of the Australian Capital Territory Legislative Assembly from 2004 to 2013 and served as leader of the Canberra Liberals and Leader of the Opposition from 2007 to 2013.\n" +
                "At the 2008 election, Seselja received a quota of 1.49 and was elected first in the seven-member Molonglo electorate. There was a decrease in the vote for both major parties, with a swing to the Greens. Labor won 7 seats, the Liberals won 6 seats, while the Greens won 4 seats, giving them the balance of power. Negotiations ensued between the Greens and both major parties over the formation of a government. After almost two weeks of deliberations, the Greens chose to support a minority Labor government, thereby consigning Seselja's party to the opposition benches.\n" +
                "At the 2012 election, Seselja moved to the five member Brindabella electorate where he received a quota of 1.8. He led the Canberra Liberals to their highest-ever number of seats, claiming eight in the seventeen-member ACT Legislative Assembly.\n");

        //0
        descsLabor.add("The Australian Labor Party (ALP; known as Labor, historically spelt Labour) is a major centre-left political party in Australia. The party has been in opposition at the federal level since the 2013 election. The party is a federal party with branches in each state and territory. Labor is in government in the states of Victoria, Queensland, Western Australia, and in both the Australian Capital Territory and Northern Territory. The party competes against the Liberal/National Coalition for political office at the federal and state (and sometimes local) levels. It is the oldest political party in Australia.\n" +
                "Labor's constitution has long stated: \"The Australian Labor Party is a democratic socialist party and has the objective of the democratic socialisation of industry, production, distribution and exchange, to the extent necessary to eliminate exploitation and other anti-social features in these fields\". This \"socialist objective\" was introduced in 1921 but was later qualified by two further objectives: \"maintenance of and support for a competitive non-monopolistic private sector\" and \"the right to own private property\". Labor governments have not attempted the \"democratic socialisation\" of any industry since the 1940s, when the Chifley Government failed to nationalise the private banks, and in fact have privatised several industries such as aviation and banking. Labor's current National Platform describes the party as \"a modern social democratic party\".\n");
        descsLabor.add("Anne Elizabeth Urquhart (née Polden; born 18 October 1957) is an Australian politician and member of the Australian Labor Party. She was elected to the Australian Senate representing Tasmania at the 2010 Australian federal election.\n" +
                "Before entering politics Urquhart first worked at the Simplot food processing factory in Ulverstone, before becoming an official with the Food Preservers' Union of Australia (FPUA). The FPUA later merged into Australian Manufacturing Workers Union and from 2004 Urquhart was the state secretary of that body in Tasmania.\n");
        descsLabor.add("William Richard Shorten (born 12 May 1967) is an Australian politician who served as Leader of the Opposition and Leader of the Labor Party from 2013 to 2019. Shorten was first elected Member of Parliament (MP) for Maribyrnong in 2007.\n" +
                "Born in Melbourne, Shorten studied law at Monash University. He worked in politics and in law before becoming an organiser with the Australian Workers' Union (AWU) in 1994. He was elected State Secretary of the Victorian Branch of the AWU in 1998 before becoming AWU National Secretary in 2001. In this role, shorten played a prominent role as a negotiator following the Beaconsfield Mine collapse in 2005, which first brought him to national prominence.\n" +
                "Shorten was elected to the House of Representatives in 2007 for the Division of Maribyrnong and was immediately appointed a Parliamentary Secretary. Following the 2010 election, he was promoted to the Cabinet, serving first as Assistant Treasurer, then as Minister for Financial Services and Superannuation and Minister for Workplace Relations in the Gillard Government. In 2013, he was briefly Minister for Education until the defeat of the Rudd Government that year.\n" +
                "Shorten stood in the subsequent leadership election against Anthony Albanese, the first such election that allowed a vote of party members as well as Members of Parliament, and was declared the winner on 13 October 2013. Shorten led Labor to gain 14 seats at the 2016 federal election, when the Coalition retained its majority by one seat.\n" +
                "Shorten announced his pending resignation after Labor's defeat in the 2019 federal election. The next day, shorten clarified that he would remain leader of the Labor Party until a new leader is elected in an upcoming leadership ballot. Shorten became the eleventh Labor Leader overall and the first since Kim Beazley to lose two consecutive elections.\n");
        descsLabor.add("Carol Louise Brown (born 19 July 1963), an Australian politician, has been an Australian Labor Party member of the Australian Senate representing the state of Tasmania since 25 August 2005.\n" +
                "Brown comes from a family with a long Labor tradition. Her great-grandmother Mary Butler was a founding member of the Hobart branch of the ALP, her grandfathers and father were strong trade unionists, her late uncle Leo Brown was a Tasmanian state ALP president, and her niece Allison Ritchie was a member of the Tasmanian Legislative Council.\n" +
                "Brown was an administrative Officer with the Tasmanian ALP from 1984 to 1996, an advisor to Senator Mackay 1996 to 1998, and a senior public servant in the Tasmanian Department of Premier and Cabinet from 1998 to 2002. In 2004 she was appointed to the Office of the Minister for Infrastructure, Energy and Resources.\n" +
                "Brown, a member of Labor's left faction, was appointed to the Senate by the Tasmanian Parliament due to the casual vacancy created by the resignation of Senator Sue Mackay.\n");
        descsLabor.add("Catryna Louise Bilyk (née Goninon; born 7 February 1959) is an Australian politician. She has been a Labor member of the Australian Senate since July 2008, representing the state of Tasmania.\n" +
                "Bilyk was elected to serve a six-year term in the Senate at the 2007 federal election, after being placed in the third position on the Australian Labor Party's Tasmanian ticket. She was elected to the sixth Senate seat for Tasmania, on preferences distributed from Andrew Wilkie, the Australian Greens' second candidate for the Senate in Tasmania in the 2007 election. It was second time lucky for Bilyk, who had also been preselected in third spot on the Labor Senate ticket in Tasmania at the 2001 federal election but failed to win a seat.\n" +
                "Bilyk was born in Hobart. She worked as an industrial officer for the Australian Services Union, a researcher for psychiatric pioneer Eric Cunningham Dax, an early childhood educator, and an advisor to Tasmanian Labor Ministers David Crean, Ken Bacon (politician) and David Llewellyn (Australian politician). She has been ALP National Vice-President. She is married with two adult children.\n" +
                "On 27 February 2016, Catryna Bilyk announced that she supports same-sex marriage.\n");
        descsLabor.add("Christopher Ronald Ketter (born 12 February 1961) is an Australian politician representing Queensland for the Australian Labor Party in the Australian Senate from 1 July 2014, as elected at the 2013 election.\n" +
                "Ketter is linked with the conservative Shop, Distributive and Allied Employees Association (SDA). Ketter was one of only two Labor Senators (along with Helen Polley) to vote against the Marriage Amendment (Definition and Religious Freedoms) Act 2017, which legalised same-sex marriage in Australia.\n");
        descsLabor.add("Deborah Mary O'Neill (born 4 June 1961) is an Australian politician who has been a Senator for New South Wales since 2013. She is a member of the Australian Labor Party and formerly represented the seat of Robertson as a member of the House of Representatives from 2010 to 2013.\n" +
                "O'Neill grew up in Western Sydney, the daughter of Irish Catholic immigrants; her mother was born in Thomastown and her father in Cork. She held Irish citizenship by descent until renouncing it prior to the 2010 election. O'Neill moved to the Central Coast when she got married. Before entering politics, she was a local teacher and a lecturer in the Faculty of Education and Arts at The University of Newcastle, Central Coast Campus.\n" +
                "O'Neill attended the University of Sydney and the University of New England where she received a Bachelor of Arts. In addition, she has also completed a Master of Arts and a Diploma of Teaching from the Australian Catholic University as well as a Graduate Diploma in Literary Education from Deakin University.\n");
        descsLabor.add("Donald Edward Farrell (born 6 June 1954) is an Australian politician and a former trade union leader.\n" +
                "He was a Labor member of the Australian Senate from 2008 to 2014, representing the state of South Australia and re-elected at the 2016 double dissolution election.\n" +
                "Appointed the Parliamentary Secretary for Sustainability and Urban Water on 14 September 2010, Farrell was promoted into the outer ministry on 25 March 2013 as the Minister for Science and Research and the Minister Assisting on Tourism, in the Second Gillard Ministry. On 1 July 2013 Farrell was appointed the Minister for Sport as well as remaining Minister Assisting on Tourism in the Second Rudd Ministry. Farrell failed in his attempt to be re-elected to the Senate at the 2013 federal election, and his first term concluded on 30 June 2014.\n");
        descsLabor.add("Douglas Niven Cameron (born 27 January 1951) is an Australian politician and trade unionist. He has been a Labor member of the Australian Senate since July 2008, representing the state of New South Wales.\n" +
                "Cameron was born in Bellshill, Scotland, just outside of Glasgow. His mother's parents were born in Lithuania. He left school at 15 to take up an apprenticeship as a fitter at a local chain-making factory. Shortly after completing his apprenticeship the factory closed, and Cameron emigrated to Australia in 1973, at the age of 22. He initially worked at the Garden Island Dockyard in Sydney, before moving to the Liddell Power Station in Muswellbrook in 1975, where he worked as a maintenance fitter. After seven years working at the power station Cameron was elected as the Hunter Valley/New England regional organiser for the Amalgamated Metal Workers and Shipwrights Union (AMWSU). In 1986 he became the Assistant State Secretary of the union (by then known as the Amalgamated Metal Workers Union) in NSW, and later the Assistant National Secretary. Cameron served as National Secretary of the Australian Manufacturing Workers Union from 1996 to 2008.\n");
        descsLabor.add("Jennifer McAllister (born 21 February 1973) is a Senator for New South Wales, and a former President of the Australian Labor Party. She is from the Socialist Left faction of the Labor Party. In August 2018 she was appointed Shadow Assistant Minister for Families and Communities. \n" +
                "McAllister was born in Murwillumbah, on the north coast of New South Wales. She attended the University of Queensland from 1992–1995, majoring in Politics and Government, and the University of Sydney, from which she graduated in 1996 with a Bachelor of Arts with First Class Honours, majoring in Political Economy, Politics and Government.\n" +
                "McAllister's first formal involvement with politics came in 1992, when she registered as a member of the Australian Labor Party. In 2003, she co-founded the Labor Environment Activist Network with Kristina Keneally, a future Premier of New South Wales.\n");
        //10
        descsLabor.add("Kim John Carr (born 2 July 1955) is an Australian politician who has been a Senator for Victoria since 1993, representing the Labor Party. He served as a minister in the Rudd and Gillard Governments.\n" +
                "Carr is a graduate of the University of Melbourne, and before entering politics worked as a schoolteacher and political staffer. He was appointed to the Senate in 1993, filling a casual vacancy, and was made a member of the shadow ministry after Labor's defeat at the 1996 election. Carr held a variety of portfolios in the Labor governments between 2007 and 2013, and is current a member of Bill Shorten's shadow cabinet. He is considered a leader of the Labor Left faction in Victoria.\n" +
                "Carr was born in Tumut, New South Wales and educated at the University of Melbourne where he obtained Bachelor of Arts with Honours and Master of Arts degrees in History and a Diploma of Education. He joined the Labor Party in 1975. He was a secondary school teacher for nine years before becoming a political staffer for Victorian government ministers Joan Kirner and Andrew McCutcheon.\n");
        descsLabor.add("Kimberley Jane Elizabeth Kitching (born 16 February 1970) is an Australian politician and former lawyer and trade unionist. She has been a Senator for Victoria since October 2016, representing the Labor Party.\n" +
                "Kitching has been involved in Victorian Labor politics for some time, including being vice-president of the party's Victorian Branch. She was a Melbourne City Councillor in the early 2000s and was a senior adviser to several ministries in the government of Labor premier Steve Bracks, as well as to John Lenders, the treasurer in the Brumby government.\n" +
                "In the 2013 Australian federal election, Kitching made a bid for Labor pre-selection for the Victorian electorates of Lalor and Gellibrand. Her bid was unsuccessful due to opposition from within the party, including from Stephen Conroy.\n" +
                "On 13 October 2016, Kitching won pre-selection to fill the Victorian Senate seat vacated by Stephen Conroy's resignation on 30 September. Kitching's pre-selection was supported by her close friend, Opposition Leader Bill Shorten, and by the Labor Right. Shorten's support for Kitching generated tension in the party with former frontbencher Anthony Albanese refusing to support her pre-selection, and legal affairs spokesperson Mark Dreyfus threatening to resign from his position in the shadow cabinet, although he did not carry out the threat.\n" +
                "Kitching was formally sworn in as a Senator on 7 November 2016.\n");
        descsLabor.add("Kristina Kerscher Keneally (born 19 December 1968) is an Australian politician who has been a Senator for New South Wales since February 2018, representing the Labor Party. Since 2019, she has served as Deputy Leader of the Opposition in the Senate, Shadow Minister for Home Affairs, and Shadow Minister for Immigration and Citizenship. She previously served as Premier of New South Wales from 2009 to 2011, the first woman to hold the position.\n" +
                "Keneally was born in the United States to an American father and an Australian mother. She grew up in Toledo, Ohio, and is a graduate of the University of Dayton. After marrying an Australian, Ben Keneally, she settled in Australia permanently and became a naturalised citizen in 2000. Keneally was elected to the New South Wales Legislative Assembly seat of Heffron at the 2003 state election, succeeding Deirdre Grusovin after a controversial preselection process. After being re-elected to parliament at the 2007 state election, she became the Minister for Ageing and Disability Services and was subsequently appointed Minister for Planning by Premier Nathan Rees in 2008. She was also the state government's spokeswoman for World Youth Day 2008.\n");
        descsLabor.add("Lisa Maria Singh (born 20 February 1972) is an Australian politician who is a Labor Party member of the Australian Senate for Tasmania. She was previously a member of the Tasmanian House of Assembly, representing the division of Denison from 2006 to 2010. The granddaughter of an Indo-Fijian member of the Parliament of Fiji, Singh is Australia's first federal parliamentarian of Indo-Fijian ancestry.\n" +
                "Following university, Singh worked in public relations and for the Australian Education Union as an industrial organiser. After joining the Australian Labor Party, Singh served on the Tasmanian ALP’s State Administrative Committee, as President of the New Town branch and as a delegate at state and national conferences.\n" +
                "From 1999–2001 Singh was as an adviser to Senator Sue Mackay. Singh then became the Director of the Tasmanian Working Women's Centre where she campaigned for paid parental leave and equal pay. Singh is a member of Emily's List, having served on the National Executive of the organisation in Australia.\n" +
                "Singh became Hobart Citizen of the Year in 2004 for her work in the peace movement surrounding the Iraq war, especially in highlighting the plight of women and children in war.\n" +
                "Singh has also served as the President of the YWCA Tasmania, the President of the United Nations Association Tasmania and as a member of the Tasmania Women's Council. Singh was Convenor of the Australian Republican Movement from 2004–2007. She subsequently managed the Tasmanian Government arts unit, arts@work, before being pre-selected for the Australian Labor Party.\n");
        descsLabor.add("Louise Clare Pratt (born 18 April 1972) is an Australian politician who has been a Senator for Western Australia since 2016, and previously from 2008 to 2014. She is a member of the Labor Party and served as a member of the Western Australian Legislative Council from 2001 to 2007. She was the youngest woman ever elected to the Legislative Council at the time of her election, the second open lesbian to be elected to an Australian parliament and was the first to have a transgender man as a partner.");
        descsLabor.add("Malarndirri Barbara Anne McCarthy (born 19 April 1970) is an Australian politician and former journalist who has been a Senator for the Northern Territory since 2016. She is a member of the Labor Party, and previously served in the Northern Territory Legislative Assembly from 2005 to 2012.\n" +
                "McCarthy was born in Katherine, Northern Territory, and grew up with her mother's family in Borroloola, on the McArthur River. She began her education in Alice Springs before moving to Sydney to board at St Scholastica's College. Prior to entering politics, McCarthy worked as a journalist and presenter for ABC News and Current Affairs. She was known as Barbara McCarthy until 2007, when she adopted her current name to honour her deceased mother.\n" +
                "In 2005, McCarthy was elected to the NT Legislative Assembly for the division of Arnhem. She was re-elected unopposed in 2008, and was subsequently appointed to the ministry by Paul Henderson. She held a number of portfolios over the following four years, but lost her seat in Labor's landslide defeat at the 2012 election. McCarthy subsequently returned to the media as a presenter for NITV and SBS News. She re-entered politics as Labor's lead Senate candidate in the Northern Territory at the 2016 federal election.\n");
        descsLabor.add("Murray Patrick Watt (born 20 January 1973) is an Australian Labor politician who was a member of the Legislative Assembly of Queensland from March 2009 to March 2012 and has represented Queensland in the Australian Senate since being elected at the July 2016 election.\n" +
                "Watt was educated at Brisbane State High School where he was School Captain in 1989. In 1996 he graduated from the University of Queensland with a Bachelor of Commerce/Bachelor of Laws. He was a solicitor (1997–2002) and judge's associate (1999–2000). He was a public servant in the Queensland Department of Premier and Cabinet and the Department of State Development (2007–09) and chief of staff to Anna Bligh (2002–07; 2008). He had long been active in the Australian Labor Party, serving as President of Queensland Young Labor in 1998 and delegate to various state conferences. In 2009 he was elected to the Legislative Assembly of Queensland for Everton, succeeding Rod Welford, who retired. He was defeated for re-election at the 2012 state election.\n" +
                "Watt was also a senior associate with the Brisbane office of Maurice Blackburn.\n" +
                "Following announcement of the retirement of Senator Jan McLucas, in 2015 Watt was endorsed as a Labor Senate candidate for Queensland at the 2016 federal election and subsequently elected.\n");
        descsLabor.add("Patrick Lionel Djargun Dodson (born 29 January 1948) is a Senator for Western Australia. He is a Yawuru man from Broome, Western Australia. He has been chairman of the Council for Aboriginal Reconciliation, Commissioner into Aboriginal Deaths in Custody, and a Roman Catholic priest. He was the winner of the 2008 Sydney Peace Prize and the 2009 John Curtin Medallist. His brother is Mick Dodson, also a national Indigenous Australian leader.\n" +
                "On 2 March 2016, Dodson was announced as the replacement for Joe Bullock as a Labor Senator for Western Australia, following Bullock's resignation. The Parliament of Western Australia appointed Dodson to the Australian Senate on 2 May 2016.\n");
        descsLabor.add("Penelope Ying-Yen Wong (born 5 November 1968) is an Australian politician who has represented South Australia in the Senate since 2002 and is the current Leader of the Opposition in the Senate and Shadow Minister for Foreign Affairs. Wong is a member of the Australian Labor Party (ALP), and was a member of the Federal Cabinet in both the Gillard Government and the first and second Rudd Governments.\n" +
                "Born in Malaysia to an Australian mother and Malaysian father, Wong was educated at Scotch College in Adelaide, and then attended the University of Adelaide, graduating with Bachelor of Arts and Bachelor of Laws degrees. Prior to entering Federal parliament, Wong worked as a lawyer and political advisor. Wong is the first Asian-born member of an Australian cabinet. She is the first female openly-LGBTI Australian federal parliamentarian and federal government cabinet minister, and supported legalising same-sex marriage in Australia despite previously opposing it.\n" +
                "First elected to the Senate at the 2001 federal election (and sitting from July 2002), Wong was named Minister for Climate Change and Water following Labor's victory under Kevin Rudd at the 2007 election. She went on to be Minister for Climate Change, Energy Efficiency and Water in early 2010. On 13 September 2010, Wong was sworn in as Minister for Finance and Deregulation following the reelection of the Gillard Government. Wong retained the position after Kevin Rudd's successful leadership spill in June 2013, and became Leader of the Government in the Senate, holding these roles until Labor's defeat at the 2013 federal election.\n");
        descsLabor.add("Raffaele \"Raff\" Ciccone (born 1 November 1983) is an Australian politician who is a Senator for Victoria, representing the Labor Party. He was appointed to the Senate on 6 March 2019 following the resignation of Jacinta Collins.\n" +
                "Ciccone joined the Australian Labor Party in 2000. Before entering the Senate, Ciccone worked as a staffer to Senator Jacinta Collins and was a vice-president of the Australian Labor Party (Victorian Branch). He was an unsuccessful candidate for Labor's Senate ticket in Victoria prior to the 2013 federal election. He also stood for election to the Monash City Council in 2008 and 2016 but was defeated with less than ten percent of the vote on each occasion.\n" +
                "Ciccone was appointed to the Senate on 6 March 2019 to fill a casual vacancy caused by the resignation of Jacinta Collins.\n");
        //20
        descsLabor.add("Susan Lines (born 15 December 1953) is an Australian politician who has been a Senator for Western Australia since 2013, representing the Labor Party. Before entering politics, she was a trade union official.\n" +
                "On 15 May 2013, a joint sitting of the Parliament of Western Australia appointed Lines to fill the casual vacancy in the Senate caused by the resignation of Senator Chris Evans. On 30 September 2016, she was elected Deputy President of the Senate in succession to Gavin Marshall. She is the third woman to hold the position, after Margaret Reid and Sue West.\n");
        descsLabor.add("Tanya Joan Plibersek (born 2 December 1969) is an Australian politician who served as Deputy Leader of the Labor Party and Deputy Leader of the Opposition from 2013 to 2019, and has served as Member of Parliament (MP) for Sydney since 1998. A member of the Labor Party, Plibersek served as a Cabinet Minister in the Rudd and Gillard Governments.\n" +
                "Plibersek was born in Sydney to Slovenian immigrant parents. She has degrees from the University of Technology Sydney and Macquarie University, and before entering parliament worked as a staffer for Senator Bruce Childs. Plibersek was elected to the Division of Sydney at the 1998 federal election, aged 28. She was added to the Shadow Cabinet in 2004, and when Labor won the 2007 election was made Minister for Housing and Minister for the Status of Women. In a cabinet reshuffle in 2010, Plibersek was instead made Minister for Human Services and Minister for Social Inclusion. She was promoted to Minister for Health the following year, and held that position until Labor's defeat at the 2013 election. Plibersek was elected deputy leader to Bill Shorten in the election's aftermath. She is a member of the Labor Left faction.\n");

        descsOther.add("The Australian Greens, commonly known as The Greens, are a green political party in Australia.\n" +
                "The party was formed in 1992 and is a confederation of eight state and territorial parties. In addition to environmentalism, the party cites four core values: ecological sustainability, social justice, grassroots democracy and peace and non-violence.\n" +
                "Party constituencies can be traced to various origins – notably the early environmental movement in Australia and the formation of the United Tasmania Group (UTG), one of the first green parties in the world, but also the nuclear disarmament movement in Western Australia and sections of the industrial left in New South Wales. Co-ordination between environmentalist groups occurred in the 1980s with various significant protests. Key people involved in these campaigns included Bob Brown and Christine Milne who went on to contest and win seats in the Tasmanian Parliament and eventually form the Tasmanian Greens; both Brown and Milne subsequently became leaders of the federal party.\n");
        descsOther.add("Richard Luigi Di Natale (born 6 June 1970) is an Australian politician who serves as a senator for Victoria and leads the Australian Greens. Di Natale was elected to the Australian Senate in the 2010 federal election. A former general practitioner, Di Natale became federal parliamentary leader of the Australian Greens on 6 May 2015 following the resignation of Christine Milne and led the Greens at the 2 July 2016 federal election.\n" +
                "Di Natale was born in Melbourne, Victoria, Australia, to Italian Catholic immigrant parents. His mother was born in San Marco in Lamis, Apulia, while his father was born in Syracuse, Sicily. Di Natale attended Parade College, graduating in 1987, and Monash University, where he graduated with a Bachelor of Medicine, Bachelor of Surgery degree in 1993. He later obtained Master of Public Health and Master of Health Science degrees from La Trobe University.\n" +
                "Prior to entering parliament, Di Natale was a general practitioner and public health specialist. He worked in Aboriginal health in the Northern Territory, on HIV prevention in India and in the drug and alcohol sector.\n");
        descsOther.add("Centre Alliance, formerly known as the Nick Xenophon Team (NXT), is a centrist Australian political party based in the state of South Australia. It presently holds two seats in the Australian Senate and one seat in the House of Representatives of Australia.\n" +
                "Since its founding in July 2013, the party has twice changed names. At the time of the 2016 Australian federal election, it was known as the Nick Xenophon Team (NXT). After the creation of SA-BEST, an affiliated state-based party created by Nick Xenophon, NXT sought to change its name to SA-BEST (Federal), but prior to Australian Electoral Commission approval Nick Xenophon departed from politics, and so the party withdrew its application and changed its name to Centre Alliance. In 2018, Centre Alliance senator Stirling Griff stated that SA-BEST is \"a separate entity, a separate association, a separate party\" from Centre Alliance.\n");
        descsOther.add("Stirling Griff (born 2 December 1957) is an Australian politician who has been a Senator for South Australia since 2016, representing the Nick Xenophon Team and Centre Alliance. His party changed its name from Nick Xenophon Team (NXT) led by Senator Nick Xenophon to Centre Alliance in April 2018 after Xenophon ceased to be connected with the party. He served as deputy leader of the party in the Senate until April 2018, when it adopted its current name. He was also the NXT spokesperson for health, immigration and communications.\n" +
                "Griff was born and raised in South Australia. He is of Jewish Lithuanian descent. He has lived and worked in Adelaide, regional South Australia and Melbourne. He is married to Kristin and has four children aged 16 to 30 in 2016.\n" +
                "Griff has worked for the Bank of Adelaide, a radio network, Readers Digest, Young & Rubicam, as a consultant, for the SA branch of the Retail Traders Association (later known as the Australian Retailers Association), and as a retail businessman in telecommunications, owning '3 Mobile' shops. Since 2013 he has been involved with Nick Xenophon, principally as his campaign manager in 2013.\n");
        descsOther.add("Pauline Hanson's One Nation (PHON or ONP), also known as One Nation or One Nation Party, is a political party in Australia. One Nation was founded in 1997, by member of parliament Pauline Hanson and her advisors David Ettridge and David Oldfield after Hanson was disendorsed as a federal candidate for the Liberal Party of Australia. The disendorsement came before the 1996 federal election because of comments she made about Indigenous Australians. Hanson sat as an independent for one year before forming Pauline Hanson's One Nation.\n" +
                "Federally, no One Nation candidate has ever been elected to the House of Representatives (Hanson was already a member of the House when One Nation was formed). However, one candidate from the party was elected to the Senate in the 1998 federal election, and four One Nation senators were elected in the 2016 federal election. In state politics, however, One Nation has performed better. At the 1998 Queensland state election the party gained more than 22% of the vote in Queensland's unicameral legislative assembly, winning 11 of the 89 seats. David Oldfield was elected to the New South Wales Legislative Council as a One Nation candidate, but he was expelled from the party and later formed the unsuccessful splinter group, One Nation NSW. Three members were elected to the Western Australian Legislative Council.\n");
        descsOther.add("Pauline Lee Hanson (née Seccombe, formerly Zagorski; born 27 May 1954) is an Australian politician who is the founder and leader of Pauline Hanson's One Nation Party (PHON). She is currently a Senator representing Queensland in the Parliament of Australia.\n" +
                "Hanson first entered politics as a member of Ipswich City Council in 1994. She joined the Liberal Party of Australia in 1995 and was preselected for the Division of Oxley at the 1996 federal election, but was disendorsed shortly before the election. Although listed on the ballot paper as the Liberal Party candidate, she won Oxley as an independent. In 1997, Hanson co-founded Pauline Hanson's One Nation, a right-wing political party with a populist and conservative platform. She lost her seat at the 1998 federal election.\n" +
                "After leaving federal parliament, Hanson contested several state and federal elections as the leader of One Nation, as the leader of Pauline Hanson's United Australia Party and as an independent. She was expelled from One Nation in 2002. A Brisbane District Court jury found Hanson guilty of electoral fraud in 2003 though the convictions were later overturned by three judges on the Queensland Court of Appeal. As a result of the convictions, Hanson spent 11 weeks in jail prior to the appeal being heard.\n" +
                "Hanson rejoined One Nation in 2013, becoming leader again the following year. At the 2016 Australian federal election she was elected to the Senate, representing Queensland, together with three other senators of her party.\n" +
                "In February 2019, Hanson was accused of sexual harassment by Senator Brian Burston in an incident dating back to 1998. Hanson has denied the claims.\n");
        descsOther.add("The Australian Conservatives was formed in July 2016 as a conservative political activist group in Australia and as a political party in February 2017. It is led by Cory Bernardi, who had been elected to the Senate for the Liberal Party, but resigned citing disagreements with the Liberal/National Coalition, its policies and leadership under Malcolm Turnbull.\n" +
                "The Family First Party and its two state parliamentarians, Dennis Hood and Robert Brokenshire, joined and merged with the Australian Conservatives in April 2017. Brokenshire was not re-elected at the 2018 state election; Hood left the Conservatives to join the Liberal Party on 26 March 2018, leaving Bernardi as the sole remaining member in federal parliament, whose present term in the senate runs until 30 June 2022.\n" +
                "In September 2017, the leaders of the Victorian branch of the Australian Christians agreed to merge the Victorian branch with the Conservatives.\n");
        descsOther.add("Cory Bernardi (born 6 November 1969) is an Australian politician. He has been a Senator representing the state of South Australia in the Australian Senate since 2006 and is the leader of the Australian Conservatives, a minor political party he founded in 2017. He is a former member of the Liberal Party of Australia, having represented the party in the Senate from 2006 to 2017. Bernardi is a staunchly conservative Roman Catholic and author of The Conservative Revolution.\n" +
                "Bernardi entered politics in 2006 when he was selected by the Liberal Party to fill a Senate seat vacancy for South Australia left by the resignation of Robert Hill. During his time in Parliament, Bernardi has attracted controversy over several statements and views. On 7 February 2017, Bernardi announced that he would be leaving the Liberal Party to form his own party—the Australian Conservatives.\n");

        List<People> peoples = new ArrayList<People>();
        peoples.add(new People("+++++++ Liberal Party +++++++", R.drawable.liberalparty, R.drawable.liberalparty, descsLiberal.get(0)));
        peoples.add(new People("Amanda Stoker", R.drawable.as, R.drawable.liberalparty, descsLiberal.get(1)));
        peoples.add(new People("Anne Ruston", R.drawable.ar, R.drawable.liberalparty,descsLiberal.get(2)));
        peoples.add(new People("Arthur Sinodinos", R.drawable.as2, R.drawable.liberalparty,descsLiberal.get(3)));
        peoples.add(new People("Bridget McKenzie", R.drawable.bm, R.drawable.liberalparty,descsLiberal.get(4)));
        peoples.add(new People("Dean Smith", R.drawable.ds, R.drawable.liberalparty,descsLiberal.get(5)));
        peoples.add(new People("Eric Abetz", R.drawable.ea, R.drawable.liberalparty,descsLiberal.get(6)));
        peoples.add(new People("James Paterson", R.drawable.jp, R.drawable.liberalparty,descsLiberal.get(7)));
        peoples.add(new People("Jane Hume", R.drawable.jh, R.drawable.liberalparty,descsLiberal.get(8)));
        peoples.add(new People("Jim Molan", R.drawable.jm, R.drawable.liberalparty,descsLiberal.get(9)));
        peoples.add(new People("John Alexander", R.drawable.ja, R.drawable.liberalparty,descsLiberal.get(10)));
        peoples.add(new People("Jonathon Duniam", R.drawable.jd, R.drawable.liberalparty,descsLiberal.get(11)));
        peoples.add(new People("Josh Frydenberg", R.drawable.jf, R.drawable.liberalparty,descsLiberal.get(12)));
        peoples.add(new People("Karen Andrews", R.drawable.ka, R.drawable.liberalparty,descsLiberal.get(13)));
        peoples.add(new People("Kevin Andrews", R.drawable.ka2, R.drawable.liberalparty,descsLiberal.get(14)));
        peoples.add(new People("Linda Reynolds", R.drawable.lr, R.drawable.liberalparty,descsLiberal.get(15)));
        peoples.add(new People("Marise Payne", R.drawable.mp, R.drawable.liberalparty,descsLiberal.get(16)));
        peoples.add(new People("Mathias Cormann", R.drawable.mc, R.drawable.liberalparty,descsLiberal.get(17)));
        peoples.add(new People("Matthew Canavan", R.drawable.mc2, R.drawable.liberalparty,descsLiberal.get(18)));
        peoples.add(new People("Michael McCormack", R.drawable.mm, R.drawable.liberalparty,descsLiberal.get(19)));
        peoples.add(new People("Michaelia Cash", R.drawable.mc3, R.drawable.liberalparty,descsLiberal.get(20)));
        peoples.add(new People("Mitch Fifield", R.drawable.mf, R.drawable.liberalparty,descsLiberal.get(21)));
        peoples.add(new People("Scott Morrison", R.drawable.sm, R.drawable.liberalparty,descsLiberal.get(22)));
        peoples.add(new People("Simon Birmingham", R.drawable.sb, R.drawable.liberalparty,descsLiberal.get(23)));
        peoples.add(new People("Tony Abbott", R.drawable.ta, R.drawable.liberalparty,descsLiberal.get(24)));
        peoples.add(new People("Zed Seselja", R.drawable.zs, R.drawable.liberalparty,descsLiberal.get(25)));

        peoples.add(new People("+++++++ Labor Party +++++++", R.drawable.laborparty, R.drawable.laborparty, descsLabor.get(0)));
        peoples.add(new People("Anne Urquhart", R.drawable.au, R.drawable.laborparty, descsLabor.get(1)));
        peoples.add(new People("Bill Shorten", R.drawable.bs, R.drawable.laborparty, descsLabor.get(2)));
        peoples.add(new People("Carol Brown", R.drawable.cb, R.drawable.laborparty, descsLabor.get(3)));
        peoples.add(new People("Catryna Bilyk", R.drawable.cb2, R.drawable.laborparty, descsLabor.get(4)));
        peoples.add(new People("Chris Ketter", R.drawable.ck, R.drawable.laborparty, descsLabor.get(5)));
        peoples.add(new People("Deborah O'Neill", R.drawable.don, R.drawable.laborparty, descsLabor.get(6)));
        peoples.add(new People("Don Farrell", R.drawable.df, R.drawable.laborparty, descsLabor.get(7)));
        peoples.add(new People("Doug Cameron", R.drawable.dc, R.drawable.laborparty, descsLabor.get(8)));
        peoples.add(new People("Jenny McAllister", R.drawable.jml, R.drawable.laborparty, descsLabor.get(9)));
        peoples.add(new People("Kim Carr", R.drawable.kc, R.drawable.laborparty, descsLabor.get(10)));
        peoples.add(new People("Kimberley Kitching", R.drawable.kk, R.drawable.laborparty, descsLabor.get(11)));
        peoples.add(new People("Kristina Keneally", R.drawable.kk2, R.drawable.laborparty, descsLabor.get(12)));
        peoples.add(new People("Lisa Singh", R.drawable.ls, R.drawable.laborparty, descsLabor.get(13)));
        peoples.add(new People("Louise Pratt", R.drawable.lp, R.drawable.laborparty, descsLabor.get(14)));
        peoples.add(new People("Malarndirri McCarthy", R.drawable.mml, R.drawable.laborparty, descsLabor.get(15)));
        peoples.add(new People("Murray Watt", R.drawable.mw, R.drawable.laborparty, descsLabor.get(16)));
        peoples.add(new People("Patrick Dodson", R.drawable.pd, R.drawable.laborparty, descsLabor.get(17)));
        peoples.add(new People("Penny Wong", R.drawable.pw, R.drawable.laborparty, descsLabor.get(18)));
        peoples.add(new People("Raff Ciccone", R.drawable.rc, R.drawable.laborparty, descsLabor.get(19)));
        peoples.add(new People("Sue Lines", R.drawable.sl, R.drawable.laborparty, descsLabor.get(20)));
        peoples.add(new People("Tanya Plibersek", R.drawable.tp, R.drawable.laborparty, descsLabor.get(21)));

        peoples.add(new People("+++++++ Greens Party +++++++", R.drawable.partyg, R.drawable.partyg, descsOther.get(0)));
        peoples.add(new People("Richard Di Natale", R.drawable.rd, R.drawable.partyg, descsOther.get(1)));
        peoples.add(new People("+++++++ Centre Alliance Party +++++++", R.drawable.partyc, R.drawable.partyc, descsOther.get(2)));
        peoples.add(new People("Stirling Griff", R.drawable.sg, R.drawable.partyc, descsOther.get(3)));
        peoples.add(new People("++++++ Pauline Hanson's One Nation Party ++++++", R.drawable.partyo, R.drawable.partyo, descsOther.get(4)));
        peoples.add(new People("Pauline Hanson", R.drawable.ph, R.drawable.partyo, descsOther.get(5)));
        peoples.add(new People("+++++++ Conservatives Party +++++++", R.drawable.partyco, R.drawable.partyco, descsOther.get(6)));
        peoples.add(new People("Cory bernardi", R.drawable.cbo, R.drawable.partyco, descsOther.get(7)));

        return peoples;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getImageId() {
        return imageId;
    }

    public void setImageId(int imageId) {
        this.imageId = imageId;
    }

    public int getImageFactionId() {
        return imageFactionId;
    }

    public void setImageFactionId(int imageId) {
        this.imageFactionId = imageFactionId;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }
}
